function VisualStimulus(repeats, savename)
repeats = repeats - 1;
%% Receptive Field Mapping
table = {'Square Size (deg)', 12, 1, 12;...
    'Square PositionX (deg)', -174, 12, 174;...
    'Square PositionY (deg)', -39, 12, 39;...
    'Square Luminance (binary)', 1, 1, 1;...
    'Timing (delay,duration,wait)', 0, 0.095, 0;...
    'Blank', 0, [], [];
    'Randomize', 1, [], [];...
    'Interleave', 0, [], [];...
    'Repeats', repeats, [], [];... % if n after 'Repeats', then n+1 rounds in total 

    'Initialization Screen (s)', 5, [],[]};
stimType = 'Receptive Field Mapping';
trials = trialStruct_RFmapFast(stimType, table);

ReceptiveFieldMapping_Fast_360degLED(trials);
trialStructSave(trials,savename, 'RF_Mapping');

% table = {'Square Size (deg)', 300, 1, 300;...
    % 'Square PositionX (deg)', -0, 12, 0;...
    % 'Square PositionY (deg)', -0, 12, 0;...
    % 'Square Luminance (binary)', 0, 1, 1;...
    % 'Timing (delay,duration,wait)', 0, 0.095, 0;...
    % 'Blank', 0, [], [];
    % 'Randomize', 1, [], [];...
    % 'Interleave', 0, [], [];...
    % 'Repeats', 49, [], [];... % if n after 'Repeats', then n+1 rounds in total 
    % 
    % 'Initialization Screen (s)', 5, [],[]};
% stimType = 'Receptive Field Mapping';
% trials = trialStruct_RFmapFast(stimType, table);
% 
% ReceptiveFieldMapping_Fast_360degLED(trials);
% trialStructSave(trials,savename, 'RF_Mapping');


end