%% random dot, optic flow stimulus creation for head fixed mice

function OpticFlow_master_dots(savename)

table = {'Square Size (deg)', 10, 1, 10;...
    'Square PositionX (deg)', -145, 10, 145;...
    'Square PositionY (deg)', -40, 10, 40;...
    'Square Luminance (binary)', 0, 1, 1;...
    'Timing (delay,duration,wait)', 0, 0.095, 0;...
    'Blank', 0, [], [];
    'Randomize', 1, [], [];...
    'Interleave', 0, [], [];...
    'Repeats', 2, [], [];... % if n after 'Repeats', then n+1 rounds in total , 2 FOR TESTING, USUALLY 49

    'Initialization Screen (s)', 5, [],[]};
stimType = 'Receptive Field Mapping';

trials = trialStruct_RFmapFast(stimType, table);
ReceptiveFieldMapping_Fast_360degLED(trials);

savename = 'Mouse09_RFmap_Fast_100ms_EB'; 
trialStructSave(trials,savename, 'Trial01');
